### PR TITLE
Some basic theme updates, and bug fixes

### PR DESCRIPTION
**Pull request by selectdev**
This update provides some fixes for the bugs that our team has discovered across the platform. We will be implementing a actual fix for the well known security issue that was caused by allowing Markdown on our platform on our next update!

### CODE REVIEW

**Comment by selectdev** [comment]
We have readded Markdown, and added DOMpurify to prevent any XSS attacks!

**Comment by selectdev** [comment]
This PR is now ready for review

**Comment by selectdev** [comment]
@Jess4Tech is needing to review before merging is possible

**Comment by selectthegang** [comment]
@override place review .Jess4Tech --desc "Placed override to merge pr"

**Pull request merged**
